### ISSUE TITLE
Feature request cgroupsv2

### ISSUE THREAD

**Issue by tiwoe** [treydock/cgroup_exporter#27]
Thank you for your effort in making this piece of software.
I was wondering if there are any plans in supporting the cgroupsv2 now default in redhat9/rocky/alma?
I am trying to monitor slurm and using those stats in xdmod or jobstat.

**Comment by treydock** [comment]
I should be able to get something put together in the coming weeks.  We are about to deploy our first RHEL9 cluster where we use this exporter so I'll be able to validate once we have the test systems online.

**Comment by treydock** [comment]
This is released initially as 1.0.0-rc.0.  I will need to do some validation at Ohio Supercomputer Center on our RHEL7 and RHEL8 clusters as well as run some validations on upcoming RHEL9 cluster.  Did some initial testing and so far at least the cgroupv2 worked and most of the cgroupv1 code remained the same.

If you run into any issues please open a new Github issue and let me know.
