### ISSUE TITLE
slurm-23.11.1 and cgroups.v2 

### ISSUE THREAD

**Issue by singhsaluja** [treydock/cgroup_exporter#29]
On RHEL-9, slurm-23.11.1 and cgroups.v2. the cgroup_exporter isn't capturing the slurm cgroup job information. 
`./cgroup_exporter --config.paths "/slurm" --log.level=debug`

It has been working smoothly with cgroups.v1 and slurm-22.05.7. Any leads on this would be appreciated. Thank you!

**Comment by treydock** [comment]
The 1.0.0-rc.0 release supports cgroup v2: https://github.com/treydock/cgroup_exporter/releases/tag/v1.0.0-rc.0

I haven't tagged as 1.0.0 yet as I need to do some more testing on our local RHEL9 cluster that was just upgraded to Slurm 23.11.5 but we're running this RC release in production.  The RC release is working just fine for cgroup v1 but need to do more testing our new RHEL9 cluster using cgroup v2.

**Comment by singhsaluja** [comment]
Thank you @treydock and my bad, switching to 1.0.0-rc0 makes it work perfectly on RHEL9. Appreciate the response and help.
