### ISSUE TITLE
clean cgroupv2 installation will not show any values

### ISSUE THREAD

**Issue by BeHom** [treydock/cgroup_exporter#39]
Hi, 
1st of all, thank you very much for providing a cgroup exporter for job schedulers.    

I tried it, but it looks like the exporter doesn't return any data on a clean cgroupv2 installation (booting with systemd.unified_cgroup_hierarchy=1).

Exporter start with systemd:
cgroup_exporter-0.9.1.linux-amd64/cgroup_exporter --config.paths /system.slice/slurmstepd.scope/ --web.listen-address :9500

Error Message as follows:
caller=cgroup_exporter.go:385 level=error msg="Error loading cgroup subsystem" path=/system.slice/slurmstepd.scope/ err="cgroups: cgroup deleted"

I can see the cgroup for slurm jobs in the /sys/fs/cgroup/system.slice/slurmstepd.scope directory.

If I boot the server without systemd.unified_cgroup_hierarchy=1 and use --config.paths /slurm everything works.

**Comment by treydock** [comment]
With cgroupv2 you use same `--config.paths=/slurm` as with cgroupv1.  This is what I use on RHEL9 that's using cgroupv2:

```
/usr/bin/cgroup_exporter \
--web.listen-address=:9306 \
--config.paths=/slurm
```

**Comment by BeHom** [comment]
will not work. It works only if I allow both cgroup V1 and v2. The main difference is the boot flag systemd.unified_cgroup_hierarchy=1 which restrict cgroupv2 only. 

cgroup_exporter-0.9.1.linux-amd64/cgroup_exporter --config.paths /slurm --web.listen-address :9500
 caller=cgroup_exporter.go:385 level=error msg="Error loading cgroup subsystem" path=/slurm err="cgroups: cgroup deleted"

**Comment by BeHom** [comment]
stat -fc %T /sys/fs/cgroup/
cgroup2fs

**Comment by treydock** [comment]
This exporter assumes cgroupv2 if this library returns the unified mode:

https://github.com/treydock/cgroup_exporter/blob/db2716929bd3c2f9eee56785674ae665436c41f8/cgroup_exporter.go#L47-L50

Logic pulled from here: https://pkg.go.dev/github.com/containerd/cgroups#readme-examples-v2-unified

I have only tested cgroupv1 on RHEL7 and RHEL8 where only RHEL8 has the option to enable v2 and I've tested on RHEL9 where cgroupv2 is the default.

This is cgroupv2:

```
$ mount -l | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
```

However I notice this in your output:

```
cgroup_exporter-0.9.1.linux-amd64
```

The version of this exporter that supports cgroupv2 is at least v1.0.0: https://github.com/treydock/cgroup_exporter/releases/tag/v1.0.0

**Comment by BeHom** [comment]
Thank you very much, my fault. Should have read the documentation more carefully and not reused older installations. 
Runs as expected with version 1.0.0.
